name: 'pull-request'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: Run the golangci-lint linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
      - name: Run unit tests
        run: make test
