name: 'release'

on:
  release:
    types: [published]

jobs:
  do-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.3'
      - name: test version
        run: echo ${{ github.event.release.tag_name }}
      - name: test use version
        run: echo myrepo.jfrog.io/docker/company/go-app/${{ github.event.release.tag_name }}
      - name: test run makefile commands
        run: make test
      - name: test run makefile commands
        run: make build